### ISSUE TITLE
No readme no documentation

### ISSUE THREAD

**Issue by ShiiFu** [Loodoor/template_blog#6]
I didn't find any readme file or any file to know how i can install the website.

I try it without help, but it's hard :
- File inclusion fail due to a wrong name (connection page)
- Class PostManager unknow (main page)
- No sql script to install database

A documentation is necessary to install the project, and to understand the code (moreover if the code has got no comments)

**Comment by Loodoor** [comment]
Hi

That's true, there isn't any documentation or anything else.
I'll try to answer to your questions.

First, we'll add a readme with a description of the steps to follow to install this blog template
Then, the file inclusion problem was solved, thanks for reporting it :)
Also, there was a script to access to a data base, but we didn't setup any for one reason : we are using json files to stock everything :) (for multiple reasons ; one is that the users can have no possibility of setting up a data base on their server)

There isn't any comments in the code because we think that it's not valuable (the functions names are "speaking" by themself, and also that often, you'll add code but not really deeply (ie. to the main page, not to the comments manager))

Thanks for your support :)

**Comment by Loodoor** [comment]
Hi, I'm closing this issue, because now (i think, tell me if i'm wrong) the readme is explaining clearly how it works, and the code is talking by itself (and often, you won't have to open the private/public/admin/utilisateurs directories to change something :) everything (more or less, i'm working on the personnalisation of the categories) can be modified in the directory projets/ or the main directory, or directly online ;)

Good luck with your projects, Loodoor (alias Folaefolc)
